# Generated by Django 3.2.25 on 2024-04-12 09:39

import django.core.validators
from django.db import migrations, models
import music_application_rev.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), music_application_rev.web.validators.validate_string_alphanumeric]),
        ),
    ]
